kodo::random_annex_base< BlockPartitioning > Class Template Reference
Base class for the random annex encoder and decoder.
#include <random_annex_base.hpp>
Public Types
typedef BlockPartitioning block_partitioning
The block partitioning scheme used.
typedef std::pair< std::set
*
< annex_info >::iterator, bool > annex_return
typedef
*
boost::random::uniform_int_distribution
*
< uint32_t > uniform_int
The uniform int distribution.
Public Member Functions
void build_annex (uint32_t annex_size, const block_partitioning &partitioning)
Protected Member Functions
uint32_t select_block (uint32_t exclude_block)
uint32_t select_symbol (uint32_t block_symbols)
Protected Attributes
uniform_int m_block_distribution
The distribution wrapping the random generator.
boost::random::mt19937 m_random_generator
The random generator.
std::vector< std::set
*
< annex_info > > m_annex
Stores the annex for every block.
std::vector
*
< boost::dynamic_bitset<> > m_reverse_annex
Stores the reverse annex.
Detailed Description
template<class BlockPartitioning>class kodo::random_annex_base< BlockPartitioning >
Base class for the random annex encoder and decoder.
Definition at line 100 of file random_annex_base.hpp.
Member Typedef Documentation
template<class BlockPartitioning> typedef std::pair<std::set<annex_info>::iterator,bool> kodo::random_annex_base< BlockPartitioning >::annex_return
Convenient typedef to make the Standard Libary insert ugly'ness a bit more nicer
Definition at line 109 of file random_annex_base.hpp.
Member Function Documentation
template<class BlockPartitioning> void kodo::random_annex_base< BlockPartitioning >::build_annex (uint32_t annex_size, const block_partitioning & partitioning) [inline]
Builds the random annex according to the given annex size and partitioning scheme
Parameters
annex_size the size of the annex
partitioning the partitioning scheme used
Definition at line 121 of file random_annex_base.hpp.
Referenced by invoke_random_annex_base(), kodo::random_annex_decoder< DecoderType, BlockPartitioning >::random_annex_decoder(), and kodo::random_annex_encoder< EncoderType, BlockPartitioning >::random_annex_encoder().
template<class BlockPartitioning> uint32_t kodo::random_annex_base< BlockPartitioning >::select_block (uint32_t exclude_block) [inline], [protected]
Selects a block from the block distribution, however with a certain block excluded
Parameters
exclude_block block excluded from the random pick
Returns
the selected block
Definition at line 224 of file random_annex_base.hpp.
Referenced by kodo::random_annex_base< BlockPartitioning >::build_annex().
template<class BlockPartitioning> uint32_t kodo::random_annex_base< BlockPartitioning >::select_symbol (uint32_t block_symbols) [inline], [protected]
Selects a symbol id
Parameters
block_symbols the number of symbols in a block
Returns
the selected block index
Definition at line 241 of file random_annex_base.hpp.
Referenced by kodo::random_annex_base< BlockPartitioning >::build_annex().
The documentation for this class was generated from the following file:
random_annex_base.hpp