kodo::rfc5052_partitioning_scheme Class Reference
RFC5052 block partitioning scheme.
#include <rfc5052_partitioning_scheme.hpp>
Public Member Functions
rfc5052_partitioning_scheme ()
Create an uninitialized partitioning scheme.
rfc5052_partitioning_scheme (uint32_t max_symbols, uint32_t max_symbol_size, uint32_t object_size)
uint32_t symbols (uint32_t block_id) const
uint32_t symbol_size (uint32_t block_id) const
uint32_t block_size (uint32_t block_id) const
uint32_t byte_offset (uint32_t block_id) const
uint32_t bytes_used (uint32_t block_id) const
uint32_t blocks () const
uint32_t object_size () const
uint32_t total_symbols () const
uint32_t total_block_size () const
Detailed Description
RFC5052 block partitioning scheme.
Takes as input the number of symbols the symbol size and the total length of an object and returns the number the number blocks to use and the symbols and symbol size needed to encode/decode an object of the given size
Definition at line 21 of file rfc5052_partitioning_scheme.hpp.
Constructor & Destructor Documentation
kodo::rfc5052_partitioning_scheme::rfc5052_partitioning_scheme (uint32_t max_symbols, uint32_t max_symbol_size, uint32_t object_size) [inline]
Constructor
Parameters
max_symbols the maximum number of symbols in a block
max_symbol_size the size in bytes of a symbol
object_size the size in bytes of the whole object
Definition at line 105 of file rfc5052_partitioning_scheme.hpp.
Member Function Documentation
uint32_t kodo::rfc5052_partitioning_scheme::block_size (uint32_t block_id) const [inline]
Parameters
block_id the block index
Returns
the size of a specific block in bytes
Definition at line 145 of file rfc5052_partitioning_scheme.hpp.
Referenced by bytes_used().
uint32_t kodo::rfc5052_partitioning_scheme::blocks () const [inline]
Returns
the total number of blocks in the object
Definition at line 187 of file rfc5052_partitioning_scheme.hpp.
uint32_t kodo::rfc5052_partitioning_scheme::byte_offset (uint32_t block_id) const [inline]
Definition at line 152 of file rfc5052_partitioning_scheme.hpp.
Referenced by bytes_used().
uint32_t kodo::rfc5052_partitioning_scheme::bytes_used (uint32_t block_id) const [inline]
Parameters
block_id the block index
Returns
the number of bytes used in a specific block
Definition at line 173 of file rfc5052_partitioning_scheme.hpp.
uint32_t kodo::rfc5052_partitioning_scheme::object_size () const [inline]
Returns
the size of the object being partitioned
Definition at line 194 of file rfc5052_partitioning_scheme.hpp.
uint32_t kodo::rfc5052_partitioning_scheme::symbol_size (uint32_t block_id) const [inline]
Parameters
block_id the block index
Returns
the size of a symbol in a specific block
Definition at line 139 of file rfc5052_partitioning_scheme.hpp.
Referenced by block_size().
uint32_t kodo::rfc5052_partitioning_scheme::symbols (uint32_t block_id) const [inline]
Parameters
block_id the block index
Returns
the number of symbols in a specific block
Definition at line 131 of file rfc5052_partitioning_scheme.hpp.
Referenced by block_size().
uint32_t kodo::rfc5052_partitioning_scheme::total_block_size () const [inline]
Returns
The total number of bytes needed to cover all blocks
Definition at line 208 of file rfc5052_partitioning_scheme.hpp.
uint32_t kodo::rfc5052_partitioning_scheme::total_symbols () const [inline]
Returns
the total number of symbols in the entire object
Definition at line 201 of file rfc5052_partitioning_scheme.hpp.
The documentation for this class was generated from the following file:
rfc5052_partitioning_scheme.hpp