kodo::mutable_shallow_symbol_storage< SuperCoder > Class Template Reference
Defines a coding layer for 'mutable' symbol storage. Allows the buffer data to be modified i.e. useful in decoders which need to access and modify the incoming symbols.
#include <shallow_symbol_storage.hpp>
Public Types
typedef shallow_symbol_storage
*
< false, SuperCoder > Super
The actual SuperCoder type.
typedef Super::value_type value_type
Public Member Functions
uint8_t * symbol (uint32_t index)
value_type * symbol_value (uint32_t index)
void copy_into_symbols (const sak::const_storage &src)
void copy_into_symbol (uint32_t index, const sak::const_storage &src)
Additional Inherited Members
Detailed Description
template<class SuperCoder>class kodo::mutable_shallow_symbol_storage< SuperCoder >
Defines a coding layer for 'mutable' symbol storage. Allows the buffer data to be modified i.e. useful in decoders which need to access and modify the incoming symbols.
Definition at line 248 of file shallow_symbol_storage.hpp.
Member Typedef Documentation
template<class SuperCoder> typedef Super::value_type kodo::mutable_shallow_symbol_storage< SuperCoder >::value_type
The value type storing the field elements used for the specified field. E.g. the binary extension field 2^8 uses uint8_t as the value_type.
Definition at line 257 of file shallow_symbol_storage.hpp.
Member Function Documentation
template<class SuperCoder> void kodo::mutable_shallow_symbol_storage< SuperCoder >::copy_into_symbol (uint32_t index, const sak::const_storage & src) [inline]
Copies an encoded / decoded symbols to the dest buffer.
Parameters
index The index of the symbol to be copied
dest The destination buffer where the symbols should be copied. The function will copy symbol_size() bytes or until the dest buffer is full.
Definition at line 300 of file shallow_symbol_storage.hpp.
Referenced by kodo::mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > >::copy_into_symbols().
template<class SuperCoder> void kodo::mutable_shallow_symbol_storage< SuperCoder >::copy_into_symbols (const sak::const_storage & src) [inline]
Definition at line 284 of file shallow_symbol_storage.hpp.
template<class SuperCoder> uint8_t* kodo::mutable_shallow_symbol_storage< SuperCoder >::symbol (uint32_t index) [inline]
Parameters
index the index number of the symbol
Returns
Returns a pointer to the symbol data. The size of the symbol data is provided by the symbol_size() function.
Definition at line 267 of file shallow_symbol_storage.hpp.
Referenced by kodo::mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > >::copy_into_symbol(), and kodo::mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > >::symbol_value().
template<class SuperCoder> value_type* kodo::mutable_shallow_symbol_storage< SuperCoder >::symbol_value (uint32_t index) [inline]
Parameters
index the index number of the symbol
Returns
Returns a layer::value_type pointer to the symbol data. The length of the symbol data is provided by the symbol_length() function.
Definition at line 278 of file shallow_symbol_storage.hpp.
The documentation for this class was generated from the following file:
shallow_symbol_storage.hpp