kodo::debug_symbol_storage< SuperCoder > Class Template Reference
Print functions for symbol storage. Using this layer the content of the symbol storage can be printed.
#include <debug_symbol_storage.hpp>
Public Types
typedef SuperCoder::field_type field_type
typedef field_type::value_type value_type
Public Member Functions
void print_storage (std::ostream &out) const
void print_storage_value (std::ostream &out) const
void print_symbol (std::ostream &out, uint32_t index) const
void print_symbol_value (std::ostream &out, uint32_t index) const
Protected Member Functions
void print_symbol_info (std::ostream &out, uint32_t index) const
Detailed Description
template<class SuperCoder>class kodo::debug_symbol_storage< SuperCoder >
Print functions for symbol storage. Using this layer the content of the symbol storage can be printed.
Todo
Todo Missing or incorrectly named unit test
This layer provides two different ways of printing the symbol data: 1) Using the print_storage() and print_symbol() functions, the data will be printed using the numeric value of the bytes stored 2) Using the print_storage_value() and print_symbol_value() functions, the data will be printed using the numeric value of the finite field used
0 I: 23 35 222 35 0 10 1 A: 33 22 19 01 10 15 2 ?: -
The lines should be interpret as in the following example:
1 A: 33 22 19 01 10 15 ^ ^ ^
 +--+ The values of the symbol storage (format depends on
 the print function used either bytes or finite field)
| +------+ The symbol state +--------+ The symbol's pivot position
A symbol's storage can be in 3 states:
A: The storage is available, but has not necessarily been initialized. I: The storage is available and has been explicitly been initialized by the user through a set_symbol() or set_symbols() call. ?: No storage is available for this symbol.
Definition at line 54 of file debug_symbol_storage.hpp.
Member Typedef Documentation
template<class SuperCoder> typedef SuperCoder::field_type kodo::debug_symbol_storage< SuperCoder >::field_type
The finite field type used e.g. fifi::binary8 for the Finite Field 2^8
Definition at line 59 of file debug_symbol_storage.hpp.
template<class SuperCoder> typedef field_type::value_type kodo::debug_symbol_storage< SuperCoder >::value_type
The value type storing the field elements used for the specified field. E.g. the binary extension field 2^8 uses uint8_t as the value_type.
Definition at line 62 of file debug_symbol_storage.hpp.
Member Function Documentation
template<class SuperCoder> void kodo::debug_symbol_storage< SuperCoder >::print_storage (std::ostream & out) const [inline]
Print all symbols stored in the storage where the symbol data is shown in bytes.
Parameters
out The output stream to print to
Definition at line 69 of file debug_symbol_storage.hpp.
template<class SuperCoder> void kodo::debug_symbol_storage< SuperCoder >::print_storage_value (std::ostream & out) const [inline]
Print all symbols stored in the storage where the symbol data is shown in bytes.
Parameters
out The output stream to print to
Definition at line 80 of file debug_symbol_storage.hpp.
template<class SuperCoder> void kodo::debug_symbol_storage< SuperCoder >::print_symbol (std::ostream & out, uint32_t index) const [inline]
Print the bytes of a symbol at a specific index to the output stream
Parameters
out The output stream to print to
index The index of symbol to print
Definition at line 92 of file debug_symbol_storage.hpp.
Referenced by kodo::debug_symbol_storage< deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< rlnc_decoder< Field > > > > > > > >::print_storage().
template<class SuperCoder> void kodo::debug_symbol_storage< SuperCoder >::print_symbol_info (std::ostream & out, uint32_t index) const [inline], [protected]
Print the bytes of a symbol at a specific index to the output stream
Parameters
out The output stream to print to
index The index of symbol to print
Definition at line 155 of file debug_symbol_storage.hpp.
Referenced by kodo::debug_symbol_storage< deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< rlnc_decoder< Field > > > > > > > >::print_symbol(), and kodo::debug_symbol_storage< deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< rlnc_decoder< Field > > > > > > > >::print_symbol_value().
template<class SuperCoder> void kodo::debug_symbol_storage< SuperCoder >::print_symbol_value (std::ostream & out, uint32_t index) const [inline]
Print finite field elements of a specific symbol's data to the output stream
Parameters
out The output stream to print to
index The index of symbol to print
Definition at line 115 of file debug_symbol_storage.hpp.
Referenced by kodo::debug_symbol_storage< deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< rlnc_decoder< Field > > > > > > > >::print_storage_value().
The documentation for this class was generated from the following file:
debug_symbol_storage.hpp