kodo::object_decoder< DecoderType, BlockPartitioning > Class Template Reference
The object decoder supports decoding objects split over multiple decoders.
#include <object_decoder.hpp>
Public Types
typedef DecoderType::factory factory
The type of factory used to build decoders.
typedef DecoderType::pointer pointer
Pointer to a decoder.
typedef BlockPartitioning block_partitioning
The block partitioning scheme used.
Public Member Functions
object_decoder (factory &decoder_factory, uint32_t object_size)
uint32_t decoders () const
pointer build (uint32_t decoder_id)
uint32_t object_size () const
Protected Attributes
factory & m_factory
The decoder factory.
block_partitioning m_partitioning
The block partitioning scheme used.
uint32_t m_object_size
Store the total object size in bytes.
Detailed Description
template<class DecoderType, class BlockPartitioning = rfc5052_partitioning_scheme>class kodo::object_decoder< DecoderType, BlockPartitioning >
The object decoder supports decoding objects split over multiple decoders.
Todo
Todo Missing or incorrectly named unit test
When an object is too large for a single encoder/decoder pair, the object decoder uses the specified partitioning scheme to determine how decoders should be constructed to cover the entire object.
Examples:
encode_decode_file.cpp.
Definition at line 30 of file object_decoder.hpp.
Constructor & Destructor Documentation
template<class DecoderType , class BlockPartitioning = rfc5052_partitioning_scheme> kodo::object_decoder< DecoderType, BlockPartitioning >::object_decoder (factory & decoder_factory, uint32_t object_size) [inline]
Constructs a new object decoder
Parameters
factory The decoder factory to use
object_size The size in bytes of the object to be decoded
Definition at line 48 of file object_decoder.hpp.
Member Function Documentation
template<class DecoderType , class BlockPartitioning = rfc5052_partitioning_scheme> pointer kodo::object_decoder< DecoderType, BlockPartitioning >::build (uint32_t decoder_id) [inline]
Builds a specific decoder
Parameters
decoder_id Specifies the decoder to build
Returns
The initialized decoder
Definition at line 71 of file object_decoder.hpp.
Referenced by kodo::deep_storage_decoder< DecoderType, BlockPartitioning >::build(), and kodo::shallow_storage_decoder< DecoderType, BlockPartitioning >::build().
template<class DecoderType , class BlockPartitioning = rfc5052_partitioning_scheme> uint32_t kodo::object_decoder< DecoderType, BlockPartitioning >::decoders () const [inline]
Returns
The number of decoders which may be created for this object
Definition at line 63 of file object_decoder.hpp.
template<class DecoderType , class BlockPartitioning = rfc5052_partitioning_scheme> uint32_t kodo::object_decoder< DecoderType, BlockPartitioning >::object_size () const [inline]
Returns
The total size of the object to decode in bytes
Definition at line 96 of file object_decoder.hpp.
Referenced by kodo::deep_storage_decoder< DecoderType, BlockPartitioning >::swap().
The documentation for this class was generated from the following file:
object_decoder.hpp