kodo::deep_symbol_storage< SuperCoder > Class Template Reference
The deep storage implementation. In this context deep means that the symbol storage contains the entire coding buffer internally.
#include <deep_symbol_storage.hpp>
Public Types
typedef SuperCoder::value_type value_type
Public Member Functions
template<class Factory >
void construct (Factory &the_factory)
Constructs the coder with the maximum parameters it will ever see. A coder may only be constructed ONCE, but initialized many times.
template<class Factory >
void initialize (Factory &the_factory)
Initializes the coder.
uint8_t * symbol (uint32_t index)
value_type * symbol_value (uint32_t index)
const uint8_t * symbol (uint32_t index) const
const value_type * symbol_value (uint32_t index) const
void swap_symbols (std::vector< uint8_t > &symbols)
void set_symbols (const sak::const_storage &symbol_storage)
void set_symbol (uint32_t index, const sak::const_storage &symbol)
void copy_symbols (const sak::mutable_storage &dest_storage) const
void copy_symbol (uint32_t index, const sak::mutable_storage &dest) const
void copy_into_symbols (const sak::const_storage &src)
void copy_into_symbol (uint32_t index, const sak::const_storage &src)
uint32_t symbols_available () const
uint32_t symbols_initialized () const
bool is_symbols_available () const
bool is_symbols_initialized () const
bool is_symbol_available (uint32_t) const
bool is_symbol_initialized (uint32_t symbol_index) const
Detailed Description
template<class SuperCoder>class kodo::deep_symbol_storage< SuperCoder >
The deep storage implementation. In this context deep means that the symbol storage contains the entire coding buffer internally.
Todo
Todo Missing or incorrectly named unit test
This is useful in cases where incoming data is to be decoded and no existing decoding buffer exist.
Definition at line 25 of file deep_symbol_storage.hpp.
Member Typedef Documentation
template<class SuperCoder> typedef SuperCoder::value_type kodo::deep_symbol_storage< SuperCoder >::value_type
The value type storing the field elements used for the specified field. E.g. the binary extension field 2^8 uses uint8_t as the value_type.
Definition at line 30 of file deep_symbol_storage.hpp.
Member Function Documentation
template<class SuperCoder> template<class Factory > void kodo::deep_symbol_storage< SuperCoder >::construct (Factory & the_factory) [inline]
Constructs the coder with the maximum parameters it will ever see. A coder may only be constructed ONCE, but initialized many times.
Parameters
the_factory The factory used to build the codec layer. Provides access to cached data and factory functions.
Definition at line 36 of file deep_symbol_storage.hpp.
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::copy_into_symbol (uint32_t index, const sak::const_storage & src) [inline]
Copies an encoded / decoded symbols to the dest buffer.
Parameters
index The index of the symbol to be copied
dest The destination buffer where the symbols should be copied. The function will copy symbol_size() bytes or until the dest buffer is full.
Definition at line 198 of file deep_symbol_storage.hpp.
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::copy_into_symbols (const sak::const_storage & src) [inline]
Definition at line 189 of file deep_symbol_storage.hpp.
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::copy_symbol (uint32_t index, const sak::mutable_storage & dest) const [inline]
Todo
Todo Change to copy_from_symbol
Definition at line 173 of file deep_symbol_storage.hpp.
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::copy_symbols (const sak::mutable_storage & dest_storage) const [inline]
Wrap our buffer in a storage object
Use the copy_storage() function to copy the data
Definition at line 154 of file deep_symbol_storage.hpp.
template<class SuperCoder> template<class Factory > void kodo::deep_symbol_storage< SuperCoder >::initialize (Factory & the_factory) [inline]
Initializes the coder.
Parameters
the_factory The factory used to build the codec layer. Provides access to cached data and factory functions.
Todo
Todo This should not be necessary - we should not use data which has not been initialized yet anyway
Definition at line 55 of file deep_symbol_storage.hpp.
template<class SuperCoder> bool kodo::deep_symbol_storage< SuperCoder >::is_symbol_available (uint32_t) const [inline]
Parameters
symbol_index The index of the symbol to check
Returns
True if the specific symbol is available. Available means where the memory is available, but which may not have been initialized through a layer::set_symbol() or layer::set_symbols() by the user. Available means where the memory is available, but not by the user.
Definition at line 231 of file deep_symbol_storage.hpp.
template<class SuperCoder> bool kodo::deep_symbol_storage< SuperCoder >::is_symbol_initialized (uint32_t symbol_index) const [inline]
Parameters
symbol_index The index of the symbol to check
Returns
True if the specific symbol is initialized. Initialized means that a symbols memory is available and has been explicitly set by the user through a layer::set_symbol() or layer::set_symbols() call. Any symbol which is initialized is also available.
Definition at line 237 of file deep_symbol_storage.hpp.
template<class SuperCoder> bool kodo::deep_symbol_storage< SuperCoder >::is_symbols_available () const [inline]
Returns
True if all symbols in the storage layer are available. Available means where the memory is available, but which may not have been initialized through a layer::set_symbol() or layer::set_symbols() by the user. Available means where the memory is available, but not by the user.
Definition at line 219 of file deep_symbol_storage.hpp.
template<class SuperCoder> bool kodo::deep_symbol_storage< SuperCoder >::is_symbols_initialized () const [inline]
Returns
True if all symbols in the storage layer is initialized. Initialized means that a symbols memory is available and has been explicitly set by the user through a layer::set_symbol() or layer::set_symbols() call. Any symbol which is initialized is also available.
Definition at line 225 of file deep_symbol_storage.hpp.
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::set_symbol (uint32_t index, const sak::const_storage & symbol) [inline]
Sets a symbol.
Parameters
index the index of the symbol into the coding block
symbol the actual data of that symbol
Definition at line 123 of file deep_symbol_storage.hpp.
Referenced by kodo::deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< full_rlnc_decoder< Field > > > > > > >::copy_into_symbol().
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::set_symbols (const sak::const_storage & symbol_storage) [inline]
Sets the storage for the source symbols. This will specify all symbols also in the case of partial data. If this is not desired then the symbols should be specified individually. This also means that it is the responsibility of the user to communicate how many of the bytes transmitted are application data.
Parameters
symbol_storage A sak::const_storage container initialized with the buffer to be use as encoding buffer.
Definition at line 105 of file deep_symbol_storage.hpp.
Referenced by kodo::deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< full_rlnc_decoder< Field > > > > > > >::copy_into_symbols().
template<class SuperCoder> void kodo::deep_symbol_storage< SuperCoder >::swap_symbols (std::vector< uint8_t > & symbols) [inline]
Parameters
index the index number of the symbol
Definition at line 95 of file deep_symbol_storage.hpp.
template<class SuperCoder> uint8_t* kodo::deep_symbol_storage< SuperCoder >::symbol (uint32_t index) [inline]
Parameters
index the index number of the symbol
Returns
Returns a pointer to the symbol data. The size of the symbol data is provided by the symbol_size() function.
Definition at line 69 of file deep_symbol_storage.hpp.
Referenced by kodo::deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< full_rlnc_decoder< Field > > > > > > >::copy_symbol(), and kodo::deep_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< full_rlnc_decoder< Field > > > > > > >::symbol_value().
template<class SuperCoder> const uint8_t* kodo::deep_symbol_storage< SuperCoder >::symbol (uint32_t index) const [inline]
Parameters
index the index number of the symbol
Returns
Returns a const pointer to the symbol data. The size of the symbol data is provided by the symbol_size() function.
Definition at line 82 of file deep_symbol_storage.hpp.
template<class SuperCoder> value_type* kodo::deep_symbol_storage< SuperCoder >::symbol_value (uint32_t index) [inline]
Parameters
index the index number of the symbol
Returns
Returns a layer::value_type pointer to the symbol data. The length of the symbol data is provided by the symbol_length() function.
Definition at line 76 of file deep_symbol_storage.hpp.
template<class SuperCoder> const value_type* kodo::deep_symbol_storage< SuperCoder >::symbol_value (uint32_t index) const [inline]
Parameters
index the index number of the symbol
Returns
Returns a const layer::value_type pointer to the symbol data. The length of the symbol data is provided by the symbol_length() function.
Definition at line 89 of file deep_symbol_storage.hpp.
template<class SuperCoder> uint32_t kodo::deep_symbol_storage< SuperCoder >::symbols_available () const [inline]
Returns
The number of symbols that are available. Available means where the memory is available, but which may not have been initialized through a layer::set_symbol() or layer::set_symbols() by the user.
Definition at line 207 of file deep_symbol_storage.hpp.
template<class SuperCoder> uint32_t kodo::deep_symbol_storage< SuperCoder >::symbols_initialized () const [inline]
Returns
The number of symbols that are initialized. Initialized means that a symbols memory is available and has been explicitly set by the user through a layer::set_symbol() or layer::set_symbols() call. Any symbol which is initialized is also available.
Definition at line 213 of file deep_symbol_storage.hpp.
The documentation for this class was generated from the following file:
deep_symbol_storage.hpp