kodo::shallow_symbol_storage< IsConst, SuperCoder > Class Template Reference
The shallow storage implementation. In this context shallow means that the symbol storage only contains pointers to some external data structure.
#include <shallow_symbol_storage.hpp>
Public Types
typedef std::conditional
*
< IsConst, typename
*
std::add_pointer< typename
*
std::add_const< uint8_t >
*
::type >::type, typename
*
std::add_pointer< uint8_t >
*
::type >::type data_ptr
typedef std::conditional
*
< IsConst, sak::const_storage,
*
sak::mutable_storage >::type storage_type
typedef SuperCoder::value_type value_type
Public Member Functions
template<class Factory >
void construct (Factory &the_factory)
Constructs the coder with the maximum parameters it will ever see. A coder may only be constructed ONCE, but initialized many times.
template<class Factory >
void initialize (Factory &the_factory)
const uint8_t * symbol (uint32_t index) const
const value_type * symbol_value (uint32_t index) const
void swap_symbols (std::vector< data_ptr > &symbols)
void set_symbols (const storage_type &symbol_storage)
void set_symbol (uint32_t index, const storage_type &symbol)
void copy_symbols (const sak::mutable_storage &dest) const
void copy_symbol (uint32_t index, const sak::mutable_storage &dest) const
uint32_t symbols_available () const
uint32_t symbols_initialized () const
bool is_symbols_available () const
bool is_symbols_initialized () const
bool is_symbol_available (uint32_t symbol_index) const
bool is_symbol_initialized (uint32_t symbol_index) const
Protected Attributes
std::vector< data_ptr > m_data
Symbol mapping.
uint32_t m_symbols_count
Symbols count.
Detailed Description
template<bool IsConst, class SuperCoder>class kodo::shallow_symbol_storage< IsConst, SuperCoder >
The shallow storage implementation. In this context shallow means that the symbol storage only contains pointers to some external data structure.
Todo
Todo Missing or incorrectly named unit test
This is useful in cases where data to be encoded already has been read into memory or if a user requires incoming data to be directly decoded into a specific buffer.
Definition at line 25 of file shallow_symbol_storage.hpp.
Member Typedef Documentation
template<bool IsConst, class SuperCoder> typedef std::conditional<IsConst, typename std::add_pointer< typename std::add_const<uint8_t>::type >::type, typename std::add_pointer<uint8_t>::type >::type kodo::shallow_symbol_storage< IsConst, SuperCoder >::data_ptr
The data pointer used will be either: IsConst = true -> const uint8_t* IsConst = false -> uint8_t*
Definition at line 37 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> typedef std::conditional<IsConst, sak::const_storage, sak::mutable_storage>::type kodo::shallow_symbol_storage< IsConst, SuperCoder >::storage_type
The storage type used will be either: IsConst = true -> sak::const_storage IsConst = false -> sak::mutable_storage
Definition at line 46 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> typedef SuperCoder::value_type kodo::shallow_symbol_storage< IsConst, SuperCoder >::value_type
The value type storing the field elements used for the specified field. E.g. the binary extension field 2^8 uses uint8_t as the value_type.
Definition at line 49 of file shallow_symbol_storage.hpp.
Member Function Documentation
template<bool IsConst, class SuperCoder> template<class Factory > void kodo::shallow_symbol_storage< IsConst, SuperCoder >::construct (Factory & the_factory) [inline]
Constructs the coder with the maximum parameters it will ever see. A coder may only be constructed ONCE, but initialized many times.
Parameters
the_factory The factory used to build the codec layer. Provides access to cached data and factory functions.
Definition at line 55 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> void kodo::shallow_symbol_storage< IsConst, SuperCoder >::copy_symbol (uint32_t index, const sak::mutable_storage & dest) const [inline]
Definition at line 171 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> void kodo::shallow_symbol_storage< IsConst, SuperCoder >::copy_symbols (const sak::mutable_storage & dest) const [inline]
Definition at line 137 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> template<class Factory > void kodo::shallow_symbol_storage< IsConst, SuperCoder >::initialize (Factory & the_factory) [inline]
Definition at line 64 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> bool kodo::shallow_symbol_storage< IsConst, SuperCoder >::is_symbol_available (uint32_t symbol_index) const [inline]
Parameters
symbol_index The index of the symbol to check
Returns
True if the specific symbol is available. Available means where the memory is available, but which may not have been initialized through a layer::set_symbol() or layer::set_symbols() by the user. Available means where the memory is available, but not by the user.
Definition at line 213 of file shallow_symbol_storage.hpp.
Referenced by kodo::shallow_symbol_storage< true, SuperCoder >::is_symbol_initialized().
template<bool IsConst, class SuperCoder> bool kodo::shallow_symbol_storage< IsConst, SuperCoder >::is_symbol_initialized (uint32_t symbol_index) const [inline]
Parameters
symbol_index The index of the symbol to check
Returns
True if the specific symbol is initialized. Initialized means that a symbols memory is available and has been explicitly set by the user through a layer::set_symbol() or layer::set_symbols() call. Any symbol which is initialized is also available.
Definition at line 219 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> bool kodo::shallow_symbol_storage< IsConst, SuperCoder >::is_symbols_available () const [inline]
Returns
True if all symbols in the storage layer are available. Available means where the memory is available, but which may not have been initialized through a layer::set_symbol() or layer::set_symbols() by the user. Available means where the memory is available, but not by the user.
Definition at line 201 of file shallow_symbol_storage.hpp.
Referenced by kodo::shallow_symbol_storage< true, SuperCoder >::is_symbols_initialized().
template<bool IsConst, class SuperCoder> bool kodo::shallow_symbol_storage< IsConst, SuperCoder >::is_symbols_initialized () const [inline]
Returns
True if all symbols in the storage layer is initialized. Initialized means that a symbols memory is available and has been explicitly set by the user through a layer::set_symbol() or layer::set_symbols() call. Any symbol which is initialized is also available.
Definition at line 207 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> void kodo::shallow_symbol_storage< IsConst, SuperCoder >::set_symbol (uint32_t index, const storage_type & symbol) [inline]
Sets a data of a symbol.
Parameters
index the index of the symbol into the coding block
symbol the actual data of that symbol
Definition at line 120 of file shallow_symbol_storage.hpp.
Referenced by kodo::shallow_symbol_storage< true, SuperCoder >::set_symbols().
template<bool IsConst, class SuperCoder> void kodo::shallow_symbol_storage< IsConst, SuperCoder >::set_symbols (const storage_type & symbol_storage) [inline]
Sets the storage for the source symbols. This will specify all symbols also in the case of partial data. If this is not desired then the symbols should be specified individually. This also means that it is the responsibility of the user to communicate how many of the bytes transmitted are application data.
Parameters
symbol_storage A sak::const_storage container initialized with the buffer to be use as encoding buffer.
Definition at line 105 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> void kodo::shallow_symbol_storage< IsConst, SuperCoder >::swap_symbols (std::vector< data_ptr > & symbols) [inline]
Definition at line 90 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> const uint8_t* kodo::shallow_symbol_storage< IsConst, SuperCoder >::symbol (uint32_t index) const [inline]
Parameters
index the index number of the symbol
Returns
Returns a const pointer to the symbol data. The size of the symbol data is provided by the symbol_size() function.
Definition at line 73 of file shallow_symbol_storage.hpp.
Referenced by kodo::shallow_symbol_storage< true, SuperCoder >::copy_symbol(), kodo::shallow_symbol_storage< true, SuperCoder >::copy_symbols(), and kodo::shallow_symbol_storage< true, SuperCoder >::symbol_value().
template<bool IsConst, class SuperCoder> const value_type* kodo::shallow_symbol_storage< IsConst, SuperCoder >::symbol_value (uint32_t index) const [inline]
Parameters
index the index number of the symbol
Returns
Returns a const layer::value_type pointer to the symbol data. The length of the symbol data is provided by the symbol_length() function.
Definition at line 84 of file shallow_symbol_storage.hpp.
template<bool IsConst, class SuperCoder> uint32_t kodo::shallow_symbol_storage< IsConst, SuperCoder >::symbols_available () const [inline]
Returns
The number of symbols that are available. Available means where the memory is available, but which may not have been initialized through a layer::set_symbol() or layer::set_symbols() by the user.
Definition at line 189 of file shallow_symbol_storage.hpp.
Referenced by kodo::shallow_symbol_storage< true, SuperCoder >::symbols_initialized().
template<bool IsConst, class SuperCoder> uint32_t kodo::shallow_symbol_storage< IsConst, SuperCoder >::symbols_initialized () const [inline]
Returns
The number of symbols that are initialized. Initialized means that a symbols memory is available and has been explicitly set by the user through a layer::set_symbol() or layer::set_symbols() call. Any symbol which is initialized is also available.
Definition at line 195 of file shallow_symbol_storage.hpp.
The documentation for this class was generated from the following file:
shallow_symbol_storage.hpp