kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder > Class Template Reference
Implements basic linear block decoder.
#include <bidirectional_linear_block_decoder.hpp>
Public Types
typedef SuperCoder::field_type field_type
typedef field_type::value_type value_type
typedef SuperCoder::factory factory
typedef DirectionPolicy direction_policy
Public Member Functions
bidirectional_linear_block_decoder ()
Constructor.
template<class Factory >
void construct (Factory &the_factory)
Constructs the coder with the maximum parameters it will ever see. A coder may only be constructed ONCE, but initialized many times.
template<class Factory >
void initialize (Factory &the_factory)
Initializes the coder.
void decode_symbol (uint8_t *symbol_data, uint8_t *symbol_coefficients)
void decode_symbol (uint8_t *symbol_data, uint32_t symbol_index)
bool is_complete () const
uint32_t rank () const
bool is_symbol_pivot (uint32_t index) const
Protected Member Functions
void update_symbol_status ()
void decode_coefficients (value_type *symbol_data, value_type *symbol_coefficients)
void swap_decode (const value_type *symbol_data, uint32_t pivot_index)
void normalize (value_type *symbol_data, value_type *symbol_id, uint32_t pivot_index)
boost::optional< uint32_t > forward_substitute_to_pivot (value_type *symbol_data, value_type *symbol_id)
void forward_substitute_from_pivot (value_type *symbol_data, value_type *symbol_id, uint32_t pivot_index)
void backward_substitute (const value_type *symbol_data, const value_type *symbol_id, uint32_t pivot_index)
void store_coded_symbol (const value_type *symbol_data, const value_type *symbol_coefficients, uint32_t pivot_index)
void store_uncoded_symbol (const value_type *symbol_data, uint32_t pivot_index)
Protected Attributes
uint32_t m_maximum_pivot
Stores the current maximum pivot index.
Detailed Description
template<class DirectionPolicy, class SuperCoder>class kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >
Implements basic linear block decoder.
Todo
Todo Missing or incorrectly named unit test
The linear block decoder expects that an encoded symbol is described by a vector of coefficients. Using these coefficients the block decoder subtracts incoming symbols until the original data has been recreated.
Definition at line 35 of file bidirectional_linear_block_decoder.hpp.
Member Typedef Documentation
template<class DirectionPolicy, class SuperCoder> typedef DirectionPolicy kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::direction_policy
The direction policy determining the direction we iterate through the coding coefficients
Definition at line 50 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> typedef SuperCoder::factory kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::factory
Definition at line 46 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> typedef SuperCoder::field_type kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::field_type
The finite field type used e.g. fifi::binary8 for the Finite Field 2^8
Definition at line 40 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> typedef field_type::value_type kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::value_type
The value type storing the field elements used for the specified field. E.g. the binary extension field 2^8 uses uint8_t as the value_type.
Definition at line 43 of file bidirectional_linear_block_decoder.hpp.
Member Function Documentation
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::backward_substitute (const value_type * symbol_data, const value_type * symbol_id, uint32_t pivot_index) [inline], [protected]
Backward substitute the found symbol into the existing symbols.
Parameters
symbol_data buffer containing the encoding symbol
symbol_id buffer containing the encoding vector
pivot_index the pivot index of the symbol in the buffers symbol_id and symbol_data
Definition at line 434 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_coefficients(), and kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_symbol().
template<class DirectionPolicy, class SuperCoder> template<class Factory > void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::construct (Factory & the_factory) [inline]
Constructs the coder with the maximum parameters it will ever see. A coder may only be constructed ONCE, but initialized many times.
Parameters
the_factory The factory used to build the codec layer. Provides access to cached data and factory functions.
Definition at line 61 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::decode_coefficients (value_type * symbol_data, value_type * symbol_coefficients) [inline], [protected]
Decodes a symbol based on the coefficients
Parameters
symbol_data buffer containing the encoding symbol
symbol_id buffer containing the encoding vector
Definition at line 172 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_symbol(), and kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::swap_decode().
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::decode_symbol (uint8_t * symbol_data, uint8_t * symbol_coefficients) [inline]
Decodes an encoded symbol according to the coding coefficients stored in the corresponding symbol_id.
Parameters
symbol_data The encoded symbol
coefficients The coding coefficients used to create the encoded symbol
Definition at line 79 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::decode_symbol (uint8_t * symbol_data, uint32_t symbol_index) [inline]
The decode function for systematic packets i.e. specific uncoded symbols.
Parameters
symbol_data The uncoded source symbol.
symbol_index The index of this uncoded symbol in the data block.
Definition at line 97 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::forward_substitute_from_pivot (value_type * symbol_data, value_type * symbol_id, uint32_t pivot_index) [inline], [protected]
Iterates the encoding vector from where a pivot has been identified and subtracts existing symbols
Parameters
symbol_data the data of the encoded symbol
symbol_id the data constituting the encoding vector
pivot_index the index of the found pivot element
Definition at line 352 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_coefficients().
template<class DirectionPolicy, class SuperCoder> boost::optional<uint32_t> kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::forward_substitute_to_pivot (value_type * symbol_data, value_type * symbol_id) [inline], [protected]
Iterates the encoding vector and subtracts existing symbols until a pivot element is found.
Parameters
symbol_data the data of the encoded symbol
symbol_id the data constituting the encoding vector
Returns
the pivot index if found.
Definition at line 294 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_coefficients().
template<class DirectionPolicy, class SuperCoder> template<class Factory > void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::initialize (Factory & the_factory) [inline]
Initializes the coder.
Parameters
the_factory The factory used to build the codec layer. Provides access to cached data and factory functions.
Definition at line 68 of file bidirectional_linear_block_decoder.hpp.
template<class DirectionPolicy, class SuperCoder> bool kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::is_complete () const [inline]
Check whether decoding is complete.
Returns
true if the decoding is complete
Definition at line 136 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::update_symbol_status().
template<class DirectionPolicy, class SuperCoder> bool kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::is_symbol_pivot (uint32_t index) const [inline]
The symbol pivot indicates whether a symbol is available to either an encoder or decoder. A coefficient generator may use this information when generating coding coefficients.
Returns
True if the symbol is available.
Definition at line 148 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::forward_substitute_from_pivot(), and kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::forward_substitute_to_pivot().
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::normalize (value_type * symbol_data, value_type * symbol_id, uint32_t pivot_index) [inline], [protected]
Iterates the encoding vector from where a pivot has been identified and subtracts existing symbols
Parameters
symbol_data the data of the encoded symbol
symbol_id the data constituting the encoding vector
pivot_index the index of the found pivot element
Definition at line 258 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_coefficients().
template<class DirectionPolicy, class SuperCoder> uint32_t kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::rank () const [inline]
The rank of a decoder states how many symbols have been decoded or partially decoded. The rank of an encoder states how many symbols are available for encoding.
Returns
the rank of the decoder or encoder
Definition at line 142 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::is_complete().
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::store_coded_symbol (const value_type * symbol_data, const value_type * symbol_coefficients, uint32_t pivot_index) [inline], [protected]
Store an encoded symbol and encoding vector with the specified pivot found.
Parameters
symbol_data buffer containing the encoding symbol
symbol_coefficients buffer containing the symbol coefficients
pivot_index the pivot index
Definition at line 515 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_coefficients().
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::store_uncoded_symbol (const value_type * symbol_data, uint32_t pivot_index) [inline], [protected]
Stores an uncoded or fully decoded symbol
Parameters
symbol_data the data for the symbol
pivot_index the pivot index of the symbol
Definition at line 548 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_symbol(), and kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::swap_decode().
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::swap_decode (const value_type * symbol_data, uint32_t pivot_index) [inline], [protected]
When adding a raw symbol (i.e. uncoded) with a specific pivot id and the decoder already contains a coded symbol in that position this function performs the proper swap between the two symbols.
Parameters
symbol_data the data for the raw symbol
pivot_index the pivot position of the raw symbol
Definition at line 213 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_symbol().
template<class DirectionPolicy, class SuperCoder> void kodo::bidirectional_linear_block_decoder< DirectionPolicy, SuperCoder >::update_symbol_status () [inline], [protected]
Updates the symbol status to decoded if the decoder reaches full rank
Definition at line 159 of file bidirectional_linear_block_decoder.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::decode_symbol().
The documentation for this class was generated from the following file:
bidirectional_linear_block_decoder.hpp