kodo::matrix< Field > Class Template Reference
Simple storage class with a matrix API for finite field elements.
#include <matrix.hpp>
Public Types
typedef Field field_type
The finite field type used.
typedef field_type::value_type value_type
The value type used in the finite field.
Public Member Functions
matrix (uint32_t rows, uint32_t columns)
value_type element (uint32_t row, uint32_t column) const
void set_element (uint32_t row, uint32_t column, value_type &value)
uint32_t row_size () const
uint32_t row_length () const
uint8_t * row (uint32_t index)
const uint8_t * row (uint32_t index) const
value_type * row_value (uint32_t index)
const value_type * row_value (uint32_t index) const
uint32_t rows () const
uint32_t columns () const
matrix transpose () const
Detailed Description
template<class Field>class kodo::matrix< Field >
Simple storage class with a matrix API for finite field elements.
Definition at line 16 of file matrix.hpp.
Constructor & Destructor Documentation
template<class Field> kodo::matrix< Field >::matrix (uint32_t rows, uint32_t columns) [inline]
Constructor
Parameters
rows The number of rows in the matrix
columns The number of columns in the matrix
Definition at line 31 of file matrix.hpp.
Member Function Documentation
template<class Field> uint32_t kodo::matrix< Field >::columns () const [inline]
Returns
The number of columns
Definition at line 123 of file matrix.hpp.
template<class Field> value_type kodo::matrix< Field >::element (uint32_t row, uint32_t column) const [inline]
Returns the element at the specific row and column in the matrix.
Parameters
row The row index
column The column index
Returns
The element stored.
Definition at line 49 of file matrix.hpp.
Referenced by kodo::matrix< Field >::transpose().
template<class Field> uint8_t* kodo::matrix< Field >::row (uint32_t index) [inline]
Return the bytes of a row at a specific index
Parameters
index The index of the row to return
Returns
The byte corresponding to the selected row.
Definition at line 87 of file matrix.hpp.
Referenced by kodo::matrix< Field >::row_value().
template<class Field> const uint8_t* kodo::matrix< Field >::row (uint32_t index) const [inline]
Return the bytes of a row at a specific index
Parameters
index The index of the row to return
Returns
The byte corresponding to the selected row.
Definition at line 94 of file matrix.hpp.
template<class Field> uint32_t kodo::matrix< Field >::row_length () const [inline]
Returns
The length of a row in the field's value_type
Definition at line 79 of file matrix.hpp.
template<class Field> uint32_t kodo::matrix< Field >::row_size () const [inline]
Returns
The size of a row in bytes
Definition at line 73 of file matrix.hpp.
template<class Field> value_type* kodo::matrix< Field >::row_value (uint32_t index) [inline]
Return a value_type pointer to a row at a specific index
Parameters
index The index of the row to return
Returns
The value_type pointer corresponding to the selected row.
Definition at line 103 of file matrix.hpp.
Referenced by kodo::matrix< Field >::element(), and kodo::matrix< Field >::set_element().
template<class Field> const value_type* kodo::matrix< Field >::row_value (uint32_t index) const [inline]
Return a value_type pointer to a row at a specific index
Parameters
index The index of the row to return
Returns
The value_type pointer corresponding to the selected row.
Definition at line 110 of file matrix.hpp.
template<class Field> uint32_t kodo::matrix< Field >::rows () const [inline]
Returns
The number of rows
Definition at line 117 of file matrix.hpp.
template<class Field> void kodo::matrix< Field >::set_element (uint32_t row, uint32_t column, value_type & value) [inline]
Sets the element at the specific row and column in the matrix.
Parameters
row The row index
column The column index
value The element to store at the specified position
Definition at line 63 of file matrix.hpp.
Referenced by kodo::matrix< Field >::transpose().
template<class Field> matrix kodo::matrix< Field >::transpose () const [inline]
Returns
A transposed version of the matrix i.e. rows and columns switched.
Definition at line 130 of file matrix.hpp.
Referenced by kodo::transpose_vandermonde_matrix< SuperCoder >::factory::construct_matrix().
The documentation for this class was generated from the following file:
matrix.hpp