kodo::linear_block_decoder_delayed< SuperCoder > Class Template Reference
Linear block decoder with delayer backwards substitution.
#include <linear_block_decoder_delayed.hpp>
Public Types
typedef SuperCoder::field_type field_type
The field we use.
typedef field_type::value_type value_type
The value_type used to store the field elements.
typedef
*
SuperCoder::direction_policy direction_policy
Access the direction policy used by the underlying decoder.
Public Member Functions
void decode_symbol (uint8_t *symbol_data, uint8_t *coefficients)
void decode_symbol (uint8_t *symbol_data, uint32_t symbol_index)
Protected Member Functions
void decode_coefficients (value_type *symbol_data, value_type *coefficients)
void final_backward_substitute ()
Detailed Description
template<class SuperCoder>class kodo::linear_block_decoder_delayed< SuperCoder >
Linear block decoder with delayer backwards substitution.
Todo
Todo Missing or incorrectly named unit test
The delayed backwards substitution can reduce the fill-in effect and can therefore improve the decoding throughput when decoding sparse symbols, in particular if the generation size is large.
Definition at line 26 of file linear_block_decoder_delayed.hpp.
Member Function Documentation
template<class SuperCoder > void kodo::linear_block_decoder_delayed< SuperCoder >::decode_coefficients (value_type * symbol_data, value_type * coefficients) [inline], [protected]
Performs the forward substitution, but waits with the final backwards substitution until full rank is achieved.
Parameters
symbol_data The buffer of the encoded symbol
coefficients The coding coefficients used to encode the symbol
Definition at line 103 of file linear_block_decoder_delayed.hpp.
Referenced by kodo::linear_block_decoder_delayed< SuperCoder >::decode_symbol().
template<class SuperCoder > void kodo::linear_block_decoder_delayed< SuperCoder >::decode_symbol (uint8_t * symbol_data, uint8_t * coefficients) [inline]
Decodes an encoded symbol according to the coding coefficients stored in the corresponding symbol_id.
Parameters
symbol_data The encoded symbol
coefficients The coding coefficients used to create the encoded symbol
Definition at line 42 of file linear_block_decoder_delayed.hpp.
template<class SuperCoder > void kodo::linear_block_decoder_delayed< SuperCoder >::decode_symbol (uint8_t * symbol_data, uint32_t symbol_index) [inline]
The decode function for systematic packets i.e. specific uncoded symbols.
Parameters
symbol_data The uncoded source symbol.
symbol_index The index of this uncoded symbol in the data block.
Definition at line 57 of file linear_block_decoder_delayed.hpp.
template<class SuperCoder > void kodo::linear_block_decoder_delayed< SuperCoder >::final_backward_substitute () [inline], [protected]
Performs the final backward substitution that transform the coding matrix from echelon form to reduce echelon form and hence fully decode the generation
Definition at line 144 of file linear_block_decoder_delayed.hpp.
Referenced by kodo::linear_block_decoder_delayed< SuperCoder >::decode_coefficients(), and kodo::linear_block_decoder_delayed< SuperCoder >::decode_symbol().
The documentation for this class was generated from the following file:
linear_block_decoder_delayed.hpp