kodo::storage_reader< EncoderType > Class Template Reference
The storage reader class reads data from a memory buffer and initializes the an encoder with data from a specific offset within the memory buffer. This class can be used in conjunction with object encoders.
#include <storage_reader.hpp>
Public Types
typedef EncoderType::pointer pointer
Pointer to the encoder used.
Public Member Functions
storage_reader (const sak::const_storage &storage)
uint32_t size () const
void read (pointer &encoder, uint32_t offset, uint32_t size)
Detailed Description
template<class EncoderType>class kodo::storage_reader< EncoderType >
The storage reader class reads data from a memory buffer and initializes the an encoder with data from a specific offset within the memory buffer. This class can be used in conjunction with object encoders.
Note that when used together with shallow_symbol_storage encoders the caller must ensure that the memory buffer remains valid throughout the life-time of the storage_reader object.
Definition at line 24 of file storage_reader.hpp.
Constructor & Destructor Documentation
template<class EncoderType> kodo::storage_reader< EncoderType >::storage_reader (const sak::const_storage & storage) [inline]
Creates a new storage reader using the memory buffer wrapped by the const_storage object.
Parameters
storage the memory buffer to use
Definition at line 36 of file storage_reader.hpp.
Member Function Documentation
template<class EncoderType> void kodo::storage_reader< EncoderType >::read (pointer & encoder, uint32_t offset, uint32_t size) [inline]
Initializes the encoder with data from the storage object.
Parameters
encoder to be initialized
offset in bytes into the storage object
size the number of bytes to use
Definition at line 53 of file storage_reader.hpp.
Referenced by TEST().
template<class EncoderType> uint32_t kodo::storage_reader< EncoderType >::size () const [inline]
Returns
the size of the storage object in bytes
Definition at line 44 of file storage_reader.hpp.
Referenced by kodo::storage_reader< EncoderType >::read(), and TEST().
The documentation for this class was generated from the following file:
storage_reader.hpp