Generic API functions
The generic API functions are functions that makes it easier to build programs that compile time can enable or disable call to various functions.
Functions
template<class T >
bool kodo::is_partial_complete (const T &t)
template<class T >
bool kodo::is_partial_complete (const boost::shared_ptr< T > &t)
template<bool what, class T >
bool kodo::is_partial_complete (const T &t, char(*)[what]=0)
template<bool what, class T >
bool kodo::is_partial_complete (const T &t, char(*)[!what]=0)
template<class T >
void kodo::print_cached_symbol_coefficients (const T &t, std::ostream &out)
template<class T >
void kodo::print_cached_symbol_coefficients (const boost::shared_ptr< T > &t, std::ostream &out)
template<bool what, class T >
void kodo::print_cached_symbol_coefficients (const T &t, std::ostream &out, char(*)[what]=0)
template<bool what, class T >
void kodo::print_cached_symbol_coefficients (const T &t, std::ostream &out, char(*)[!what]=0)
template<class T >
void kodo::print_cached_symbol_data (const T &t, std::ostream &out)
template<class T >
void kodo::print_cached_symbol_data (const boost::shared_ptr< T > &t, std::ostream &out)
template<bool what, class T >
void kodo::print_cached_symbol_data (const T &t, std::ostream &out, char(*)[what]=0)
template<bool what, class T >
void kodo::print_cached_symbol_data (const T &t, std::ostream &out, char(*)[!what]=0)
template<class T >
void kodo::print_decoder_state (const T &t, std::ostream &out)
template<class T >
void kodo::print_decoder_state (const boost::shared_ptr< T > &t, std::ostream &out)
template<bool what, class T >
void kodo::print_decoder_state (const T &t, std::ostream &out, char(*)[what]=0)
template<bool what, class T >
void kodo::print_decoder_state (const T &t, std::ostream &out, char(*)[!what]=0)
Detailed Description
The generic API functions are functions that makes it easier to build programs that compile time can enable or disable call to various functions.
Function Documentation
template<class T > bool kodo::is_partial_complete (const T & t) [inline]
Generic function overload for cases where is_partial_complete is part of a stack.
See Also
partial_decoding_tracker::is_partial_complete() const
Parameters
t The stack to query
Definition at line 19 of file is_partial_complete.hpp.
Referenced by kodo::is_partial_complete().
template<class T > bool kodo::is_partial_complete (const boost::shared_ptr< T > & t) [inline]
Generic function overload for cases where is_partial_complete is part of a stack.
See Also
partial_decoding_tracker::is_partial_complete() const
Parameters
t The stack to query
Definition at line 27 of file is_partial_complete.hpp.
template<bool what, class T > bool kodo::is_partial_complete (const T & t, char(*) [what] = 0) [inline]
Generic function overload for cases where is_partial_complete is part of a stack.
See Also
partial_decoding_tracker::is_partial_complete() const
Parameters
t The stack to query
Definition at line 35 of file is_partial_complete.hpp.
template<bool what, class T > bool kodo::is_partial_complete (const T & t, char(*) [!what] = 0) [inline]
Generic function overload for cases where is_partial_complete is part of a stack.
See Also
partial_decoding_tracker::is_partial_complete() const
Parameters
t The stack to query
Definition at line 45 of file is_partial_complete.hpp.
template<class T > void kodo::print_cached_symbol_coefficients (const T & t, std::ostream & out) [inline]
Generic function overload for cases where print_decoder_state is part of a stack.
See Also
layer::print_cached_symbol_coefficients(std::ostream&) const
Parameters
t The stack to query
out The output stream where we will write the debug info
Definition at line 21 of file print_cached_symbol_coefficients.hpp.
Referenced by kodo::print_cached_symbol_coefficients().
template<class T > void kodo::print_cached_symbol_coefficients (const boost::shared_ptr< T > & t, std::ostream & out) [inline]
Generic function overload for cases where print_decoder_state is part of a stack.
See Also
layer::print_cached_symbol_coefficients(std::ostream&) const
Parameters
t The stack to query
out The output stream where we will write the debug info
Definition at line 29 of file print_cached_symbol_coefficients.hpp.
template<bool what, class T > void kodo::print_cached_symbol_coefficients (const T & t, std::ostream & out, char(*) [what] = 0) [inline]
Definition at line 38 of file print_cached_symbol_coefficients.hpp.
template<bool what, class T > void kodo::print_cached_symbol_coefficients (const T & t, std::ostream & out, char(*) [!what] = 0) [inline]
Definition at line 49 of file print_cached_symbol_coefficients.hpp.
template<class T > void kodo::print_cached_symbol_data (const T & t, std::ostream & out) [inline]
Generic function overload for cases where print_decoder_state is part of a stack.
See Also
layer::print_cached_symbol_data(std::ostream&) const
Parameters
t The stack to query
out The output stream where we will write the debug info
Definition at line 21 of file print_cached_symbol_data.hpp.
Referenced by kodo::print_cached_symbol_data().
template<class T > void kodo::print_cached_symbol_data (const boost::shared_ptr< T > & t, std::ostream & out) [inline]
Generic function overload for cases where print_decoder_state is part of a stack.
See Also
layer::print_cached_symbol_data(std::ostream&) const
Parameters
t The stack to query
out The output stream where we will write the debug info
Definition at line 29 of file print_cached_symbol_data.hpp.
template<bool what, class T > void kodo::print_cached_symbol_data (const T & t, std::ostream & out, char(*) [what] = 0) [inline]
Definition at line 38 of file print_cached_symbol_data.hpp.
template<bool what, class T > void kodo::print_cached_symbol_data (const T & t, std::ostream & out, char(*) [!what] = 0) [inline]
Definition at line 49 of file print_cached_symbol_data.hpp.
template<class T > void kodo::print_decoder_state (const T & t, std::ostream & out) [inline]
Generic function overload for cases where print_decoder_state is part of a stack.
See Also
debug_linear_block_decoder::print_decoder_state() const
Parameters
t The stack to query
out The output stream where we will write the debug info
Definition at line 22 of file print_decoder_state.hpp.
Referenced by kodo::print_decoder_state().
template<class T > void kodo::print_decoder_state (const boost::shared_ptr< T > & t, std::ostream & out) [inline]
Generic function overload for cases where print_decoder_state is part of a stack.
See Also
debug_linear_block_decoder::print_decoder_state() const
Parameters
t The stack to query
out The output stream where we will write the debug info
Definition at line 30 of file print_decoder_state.hpp.
template<bool what, class T > void kodo::print_decoder_state (const T & t, std::ostream & out, char(*) [what] = 0) [inline]
Definition at line 39 of file print_decoder_state.hpp.
template<bool what, class T > void kodo::print_decoder_state (const T & t, std::ostream & out, char(*) [!what] = 0) [inline]
Definition at line 50 of file print_decoder_state.hpp.