kodo Namespace Reference
Here we define the stacks which should be tested.
Classes
class aligned_coefficients_buffer
Helper layer for layers that require a buffer for storing symbol coefficients. The storage is uninitialized. The buffer is guaranteed to be aligned (on a 16 byte boundary).
class aligned_coefficients_decoder
Aligns the symbol coefficient buffer if necessary.
class backward_linear_block_decoder
struct backward_linear_block_decoder_policy
class bidirectional_linear_block_decoder
Implements basic linear block decoder.
class cached_symbol_decoder
This layer extracts the symbol coefficients and symbol data and makes it available for use. It does not perform any decoding on the coefficients or the symbol.
class coefficient_info
Provides info about the coding coefficients used during encoding and decoding.
class coefficient_storage
Provides storage and access to the coding coefficients used during encoding and decoding.
class coefficient_value_access
Provides functions to access and manipulate values in an array of coefficients.
class copy_payload_decoder
Make decoder work on a copy of the payload.
class debug_cached_symbol_decoder
This layer makes it easy to print the incoming coded symbol and coding coefficients.
class debug_coefficient_storage
Print functions for coefficient storage.
class debug_linear_block_decoder
Debug layer which allows inspecting the state of a linear block decoder.
class debug_symbol_storage
Print functions for symbol storage. Using this layer the content of the symbol storage can be printed.
class deep_storage_decoder
A storage decoder creates a number of decoders decoding into a sak::mutable_storage object.
class deep_symbol_storage
The deep storage implementation. In this context deep means that the symbol storage contains the entire coding buffer internally.
class empty_decoder
Empty implementation of the decode_symbol(uint8_t*,uint8_t*) and decode_symbol(uint8_t*, uint32_t) functions.
class encode_symbol_tracker
Counts the number of symbols which have been encoded.
class fake_symbol_storage
Implements the Symbol Storage API but only with empty functions. Useful in unit tests.
class file_encoder
A file encoder creates a number of encoders over the data of a file.
class file_reader
The file reader class reads data from a local file and initializes the an encoder with data from a specific offset within the file. This class can be used in conjunction with object encoders.
class final_coder_factory
class final_coder_factory_pool
class finite_field_counter
class finite_field_info
class finite_field_math
Basic layer performing common finite field operation.
class forward_linear_block_decoder
Implements basic linear block decoder using the forward direction policy. This is equivalent to the standard approach to Gaussian Elimination.
struct forward_linear_block_decoder_policy
struct has_debug_cached_symbol_decoder
struct has_debug_linear_block_decoder
struct has_deep_symbol_storage
struct has_linear_block_decoder_delayed
struct has_partial_decoding_tracker
class has_print_cached_symbol_coefficients
class has_print_cached_symbol_data
struct has_shallow_symbol_storage
struct has_const_shallow_symbol_storage
Type trait helper for detection the const_shallow_symbol_storage.
struct has_mutable_shallow_symbol_storage
Type trait helper for detection the mutable_shallow_symbol_storage.
class largest_nonzero_index_decoder
This layer can be added to a decoding stack to monitor the coding coefficients passed to a decoder. This specific layer tracks the largest index where it have seen non-zero coefficients. One use-case of this is to monitor when partial decoding is possible i.e. when symbols in decoder are fully decoded even though the full data block has not been sent.
class linear_block_decoder_delayed
Linear block decoder with delayer backwards substitution.
class linear_block_encoder
A linear block encoder.
class matrix
Simple storage class with a matrix API for finite field elements.
class nocode_carousel_encoder
For testing purposes this encoder implements a simple repetition code i.e. the symbols are the original source symbols produced by the encoder in a round-robin fashion.
class nocode_carousel_decoder
For testing purposes this decoder will takes symbols produced by the carousel encoder and put them in the right order until all symbols have been received.
class carousel_common
class carousel_decoder
Carousel decoder takes symbols produced by a carousel encoder and decodes them.
class carousel_encoder
Simple un-coded scheme not meant for practical use but for simulation purposes. As it simply produces un-coded symbols.
class nocode_decoder
class nocode_encoder
class object_decoder
The object decoder supports decoding objects split over multiple decoders.
class object_encoder
The object encoder, allows encoding of objects too large for a single block encoder.
class offset_coefficient_value_access
Provides functions to access and manipulate values in an array of coefficients, but with an added offset to the indexes.
struct operations_counter
class partial_decoding_tracker
This layer can be added to a decoding stack to track when partial decoding is possible i.e. when symbols in decoder are fully decoded even though the full data block has not been sent.
class partial_shallow_symbol_storage
Same as a shallow storage but supports storage object with a total size less than the coding block size.
class payload_decoder
The payload decoder splits the payload buffer into symbol header and symbol.
class payload_encoder
The payload encoder splits the payload buffer into symbol header and symbol.
class payload_rank_decoder
The payload decoder splits the payload buffer into symbol header and symbol.
class payload_rank_encoder
The payload rank encoder writes the rank of the encoder into the payload buffer.
class payload_rank_recoder
The payload rank recoder writes the rank of the encoder into the payload buffer.
class payload_recoder
Implements the recode function for Network Codes.
class plain_symbol_id
Base class for the plain symbol id reader and writer.
class base_plain_symbol_id_reader
Reads the coding coefficients from the symbol id buffer and initializes the symbol coefficients pointer. This implementation is the most basic one where the symbol id simply is the coding coefficients.
class plain_symbol_id_reader
Reads the coding coefficients from the symbol id buffer and initializes the symbol coefficients pointer. This implementation is the most basic one where the symbol id simply is the coding coefficients.
class base_plain_symbol_id_writer
Writes the symbol id and initializes the coding coefficients pointer. This implementation is the most basic one where the symbol id simply is the coding coefficients.
class plain_symbol_id_writer
Writes the symbol id and initializes the coding coefficients pointer. This implementation is the most basic one where the symbol id simply is the coding coefficients.
class proxy_layer
Special layer used to create parallel stacks with some shared layers.
class proxy_seen_encoder_rank
The proxy_seen_encoder_rank will forward calls to the seen_encoder_rank() function to a main stack.
struct annex_info
Annex info helper class.
class random_annex_base
Base class for the random annex encoder and decoder.
class random_annex_decoder
A random annex decoder.
class random_annex_encoder
A random annex encoder.
class rank_callback_decoder
Allows a callback function to be invoked after rank changed.
class rank_info
provides the layer::rank_type typedef
class rank_symbol_decoding_status_updater
This layer can be added to a decoding stack to update the status of the different decoding symbols. The functionality makes it possible for a user to detect when partial decoding is possible i.e. when symbols in decoder are fully decoded even though the full data block has not been sent.
class recoding_symbol_id
Randomly recombines existing coding coefficients to allow a decoder to produce recoded packets.
class rfc5052_partitioning_scheme
RFC5052 block partitioning scheme.
class full_rlnc_encoder
Complete stack implementing a RLNC encoder.
class recoding_stack
class full_rlnc_decoder
Implementation of a complete RLNC decoder.
class debug_full_rlnc_decoder
Implementation of a full_rlnc_decoder, but with the debug layers added.
class on_the_fly_encoder
Complete stack implementing a full RLNC on-the-fly encoder.
class on_the_fly_recoding_stack
class on_the_fly_decoder
Implementation of a complete RLNC decoder.
class debug_on_the_fly_decoder
Implementation of a complete RLNC decoder.
class seed_rlnc_encoder
Complete stack implementing a seed based RLNC encoder.
class seed_rlnc_decoder
Implementation of a seed based RLNC decoder this configuration.
class rs_encoder
Complete stack implementing a Reed-Solomon encoder.
class rs_decoder
Implementation of a complete RS decoder.
class reed_solomon_symbol_id
Base class for the Reed-Solomon symbol id reader and writer. Contains the functionality to cache the generator matrices.
class reed_solomon_symbol_id_reader_base
Reads the row index of the Reed-Solomon generator matrix from the symbol id buffer. This is then use to fetch the corresponding coding coefficients.
class reed_solomon_symbol_id_reader
Reads the row index of the Reed-Solomon generator matrix from the symbol id buffer. This is then use to fetch the corresponding coding coefficients.
class reed_solomon_symbol_id_writer
Uses the count of the currently encoded symbol to select the proper row in the generator matrix. The row is selected using the encoded symbol count.
class systematic_vandermonde_matrix
Computes a Vandermonde matrix to generate the coding coefficients. The matrix code is.
class systematic_vandermonde_matrix_base
Computes a Vandermonde matrix to generate the coding coefficients. The matrix code is.
class transpose_vandermonde_matrix
Construct the transposes the Vandermonde matrix in order to make memory access more efficient.
class vandermonde_matrix
Computes a Vandermonde matrix to generate the coding coefficients. The matrix code is.
class vandermonde_matrix_base
Computes a Vandermonde matrix to generate the coding coefficients. The matrix code is.
class seed_symbol_id
Base layer for seed symbol id reader and writers.
class seed_symbol_id_reader
Reads the seed from the symbol_id buffer and uses it to seed the generator layer, which produces the corresponding coding coefficients.
class seed_symbol_id_writer
Writes a seed as the symbol id. The seed is used to seed the generator layer before generating the coefficients. The current symbol count is used as the seed. Which allows the decoder to reproduce the coefficients used.
class shallow_storage_decoder
A storage decoder creates a number of decoders decoding into a sak::mutable_storage object.
class shallow_symbol_storage
The shallow storage implementation. In this context shallow means that the symbol storage only contains pointers to some external data structure.
class const_shallow_symbol_storage
Defines a coding layer for 'const' symbol storage. Only useful for encoders since these to modify the buffers / data they operate on.
class mutable_shallow_symbol_storage
Defines a coding layer for 'mutable' symbol storage. Allows the buffer data to be modified i.e. useful in decoders which need to access and modify the incoming symbols.
class sparse_uniform_generator
Generate uniformly distributed coefficients with a specific density.
class storage_aware_encoder
Implements the layer::rank() and layer::is_symbol_pivot() functions based on the storage status.
class storage_aware_generator
The storage aware generator will ensure that layer::generate_partial(uint8_t*) is called whenever the encoder indicates that it does not have full rank (i.e. not all symbols have been specified).
class storage_block_info
Defines several functions to retrieve info about the symbol storage layers.
class storage_bytes_used
Provides access to the number of useful bytes used out of the total size of the encoders or decoders storage.
class storage_encoder
A storage encoder creates a number of encoders over a sak::const_storage object.
class storage_reader
The storage reader class reads data from a memory buffer and initializes the an encoder with data from a specific offset within the memory buffer. This class can be used in conjunction with object encoders.
class symbol_decoding_status_counter
The symbol decoding status counter maintains information about how many symbols are in which state.
class symbol_decoding_status_tracker
The symbol decoding status tracker stores information about the status of the different symbols contained within a decoder.
class symbol_id_decoder
Writes the symbol id into the symbol header. Generates the the symbol coding coefficients. and calls the layer::decode_symbol() function.
class symbol_id_encoder
Writes the symbol id into the symbol header. Generates the the symbol coding coefficients. and calls the layer::encode_symbol() function.
class systematic_base_coder
class systematic_decoder
Systematic decoding layer.
class base_systematic_encoder
Systematic encoding layer.
class systematic_encoder
class non_systematic_encoder
class uniform_generator
Generates an uniform random coefficient (from the chosen Finite Field) for every symbol.
class user_defined_generator
This layer allows the user to specify the coefficients which be used for the coding operation.
class zero_symbol_encoder
Zeros the symbol data buffer.
class fake_codec_layer
class rlnc_decoder
class shallow_rlnc_encoder
Encoder stack using a partial shallow storage class.
class shallow_rlnc_decoder
class full_rlnc_callback_decoder
class symbol_info_decoder
The symbol info stack defined below can be used to split an incoming encoded payload into the encoded symbol data and symbol id (the RLNC encoding vector).
Functions
template<class T >
bool is_partial_complete (const T &t)
template<class T >
bool is_partial_complete (const boost::shared_ptr< T > &t)
template<bool what, class T >
bool is_partial_complete (const T &t, char(*)[what]=0)
template<bool what, class T >
bool is_partial_complete (const T &t, char(*)[!what]=0)
operations_counter operator- (const operations_counter &a, const operations_counter &b)
operations_counter operator+ (const operations_counter &a, const operations_counter &b)
bool operator>= (const operations_counter &a, const operations_counter &b)
template<class T >
void print_cached_symbol_coefficients (const T &t, std::ostream &out)
template<class T >
void print_cached_symbol_coefficients (const boost::shared_ptr< T > &t, std::ostream &out)
template<bool what, class T >
void print_cached_symbol_coefficients (const T &t, std::ostream &out, char(*)[what]=0)
template<bool what, class T >
void print_cached_symbol_coefficients (const T &t, std::ostream &out, char(*)[!what]=0)
template<class T >
void print_cached_symbol_data (const T &t, std::ostream &out)
template<class T >
void print_cached_symbol_data (const boost::shared_ptr< T > &t, std::ostream &out)
template<bool what, class T >
void print_cached_symbol_data (const T &t, std::ostream &out, char(*)[what]=0)
template<bool what, class T >
void print_cached_symbol_data (const T &t, std::ostream &out, char(*)[!what]=0)
template<class T >
void print_decoder_state (const T &t, std::ostream &out)
template<class T >
void print_decoder_state (const boost::shared_ptr< T > &t, std::ostream &out)
template<bool what, class T >
void print_decoder_state (const T &t, std::ostream &out, char(*)[what]=0)
template<bool what, class T >
void print_decoder_state (const T &t, std::ostream &out, char(*)[!what]=0)
uint32_t max_annex_size (uint32_t max_symbols, uint32_t max_symbol_size, uint32_t object_size)
bool operator< (const annex_info &a, const annex_info &b)
Allows our annex info class to be used in e.g. a std::set.
template<class SuperCoder >
bool is_systematic_encoder_dispatch (const systematic_encoder< SuperCoder > *)
template<class SuperCoder >
bool is_systematic_on_dispatch (systematic_encoder< SuperCoder > *e)
template<class SuperCoder >
void set_systematic_off_dispatch (systematic_encoder< SuperCoder > *e)
template<class SuperCoder >
void set_systematic_on_dispatch (systematic_encoder< SuperCoder > *e)
bool is_systematic_encoder_dispatch (...)
template<class Encoder >
bool is_systematic_encoder (const Encoder &e)
template<class Encoder >
bool is_systematic_encoder (const boost::shared_ptr< Encoder > &e)
bool is_systematic_on_dispatch (...)
template<class Encoder >
bool is_systematic_on (Encoder &e)
template<class Encoder >
bool is_systematic_on (boost::shared_ptr< Encoder > &e)
void set_systematic_off_dispatch (...)
template<class Encoder >
void set_systematic_off (Encoder &e)
template<class Encoder >
void set_systematic_off (boost::shared_ptr< Encoder > &e)
void set_systematic_on_dispatch (...)
template<class Encoder >
void set_systematic_on (Encoder &e)
template<class Encoder >
void set_systematic_on (boost::shared_ptr< Encoder > &e)
Detailed Description
Here we define the stacks which should be tested. Defines a number test stacks which contains the layers we wish to test. The stacks we define below contain the expect layers used in a typical coefficient storage stack. In addition to this we test both with and without adding the factory pool layer. This layer will recycle the allocated objects.
Tests:
layer::initialize(uint32_t,uint32_t)
layer::decode(const uint8_t*)
Tests:
layer::initialize(uint32_t,uint32_t)
layer::decode_symbol(uint8_t*,uint8_t*)
layer::decode_symbol(uint8_t*,uint32_t)
layer::set_rank_changed_callback()
layer::reset_rank_changed_callback()
Defines a number test stacks which contains the layers we wish to test. The stacks we define below contain the expect layers used in a typical storage stack. In addition to this we test both with and without adding the factory pool layer. This layer will recycle the allocated objects.
Function Documentation
template<class Encoder > bool kodo::is_systematic_encoder (const Encoder & e) [inline]
Returns whether an encoder has systematic capabilities this is sometimes needed when writing generic code that works with many different encoder types. Different encoders should overload / specialize this function to return true if they support the systematic operations.
Parameters
e the encoder
Returns
true if the encoder supports the systematic operations otherwise false
Examples:
encode_decode_file.cpp, and switch_systematic_on_off.cpp.
Definition at line 46 of file systematic_operations.hpp.
Referenced by is_systematic_encoder().
template<class Encoder > bool kodo::is_systematic_encoder (const boost::shared_ptr< Encoder > & e) [inline]
Helper for unwrapping encoders stored in a shared_ptr
Parameters
e the encoder
Returns
true if the encoder supports the systematic operations otherwise false
Definition at line 60 of file systematic_operations.hpp.
bool kodo::is_systematic_encoder_dispatch (...) [inline]
Catch all implementation if no specializations exist this function will be called.
Returns
always return false
Definition at line 28 of file systematic_operations.hpp.
template<class SuperCoder > bool kodo::is_systematic_encoder_dispatch (const systematic_encoder< SuperCoder > *) [inline]
Overload for the generic is_systematic_encoder_dispatch(...) function
Parameters
e the encoder
Returns
true since this is an systematic encoder
Definition at line 220 of file systematic_encoder.hpp.
Referenced by is_systematic_encoder().
template<class Encoder > bool kodo::is_systematic_on (Encoder & e) [inline]
Returns whether the encoder is in the systematic mode i.e. it is generating un-coded symbols
Parameters
e the encoder
Returns
true if the encoder is in the systematic state
Examples:
switch_systematic_on_off.cpp.
Definition at line 87 of file systematic_operations.hpp.
Referenced by is_systematic_on().
template<class Encoder > bool kodo::is_systematic_on (boost::shared_ptr< Encoder > & e) [inline]
Helper for unwrapping encoders stored in a shared_ptr
Parameters
e the encoder
Returns
true if the encoder is in the systematic state
Definition at line 100 of file systematic_operations.hpp.
bool kodo::is_systematic_on_dispatch (...) [inline]
Catch all implementation if no specializations exist this function will be called.
Returns
always return false
Definition at line 69 of file systematic_operations.hpp.
template<class SuperCoder > bool kodo::is_systematic_on_dispatch (systematic_encoder< SuperCoder > * e) [inline]
Overload for the generic is_systematic_on_dispatch(...) function
Parameters
e the encoder
Returns
true if the encoder currently produces systematic symbols
Definition at line 234 of file systematic_encoder.hpp.
Referenced by is_systematic_on().
uint32_t kodo::max_annex_size (uint32_t max_symbols, uint32_t max_symbol_size, uint32_t object_size)
Todo
Todo Missing or incorrectly named unit test For a given selection of object partitioning parameters this function returns the maximum allowed annex size.
The result returned from this function is guaranteed to work for any partitioning scheme as long as the maximum symbol size is not changed and maximum number of symbols per block is not increased.
Definition at line 29 of file random_annex_base.hpp.
Referenced by invoke_max_annex_size().
operations_counter kodo::operator+ (const operations_counter & a, const operations_counter & b) [inline]
Subtract two operations counters ala. a + b
Parameters
a The operations counter to be reduced
b The operations counter subtracted from a
Definition at line 83 of file operations_counter.hpp.
operations_counter kodo::operator- (const operations_counter & a, const operations_counter & b) [inline]
Subtract two operations counters ala. a - b
Parameters
a The operations counter to be reduced
b The operations counter subtracted from a
Definition at line 52 of file operations_counter.hpp.
bool kodo::operator>= (const operations_counter & a, const operations_counter & b) [inline]
Implement the greater than or equal operator such as a >= b
Parameters
a The first operations counter
b The second operations counter
Definition at line 115 of file operations_counter.hpp.
template<class Encoder > void kodo::set_systematic_off (Encoder & e) [inline]
Switches the systematic encoding off - i.e. stop generating un-coded symbols.
Parameters
e the encoder
Examples:
encode_decode_file.cpp, and switch_systematic_on_off.cpp.
Definition at line 125 of file systematic_operations.hpp.
Referenced by set_systematic_off().
template<class Encoder > void kodo::set_systematic_off (boost::shared_ptr< Encoder > & e) [inline]
Helper for unwrapping encoders stored in a shared_ptr
Parameters
e the encoder
Definition at line 137 of file systematic_operations.hpp.
void kodo::set_systematic_off_dispatch (...) [inline]
Catch all implementation if no specializations exist this function will be called.
Returns
always return false
Definition at line 109 of file systematic_operations.hpp.
template<class SuperCoder > void kodo::set_systematic_off_dispatch (systematic_encoder< SuperCoder > * e) [inline]
Overload for the generic set_systematic_off_dispatch(...) function
Parameters
e the encoder
Definition at line 248 of file systematic_encoder.hpp.
Referenced by set_systematic_off().
template<class Encoder > void kodo::set_systematic_on (Encoder & e) [inline]
Switches the systematic encoding on - i.e. start generating un-coded symbols.
Parameters
e the encoder
Examples:
switch_systematic_on_off.cpp.
Definition at line 162 of file systematic_operations.hpp.
Referenced by set_systematic_on().
template<class Encoder > void kodo::set_systematic_on (boost::shared_ptr< Encoder > & e) [inline]
Helper for unwrapping encoders stored in a shared_ptr
Parameters
e the encoder
Definition at line 174 of file systematic_operations.hpp.
void kodo::set_systematic_on_dispatch (...) [inline]
Catch all implementation if no specializations exist this function will be called.
Returns
always return false
Definition at line 146 of file systematic_operations.hpp.
template<class SuperCoder > void kodo::set_systematic_on_dispatch (systematic_encoder< SuperCoder > * e) [inline]
Overload for the generic set_systematic_on_dispatch(...) function
Parameters
e the encoder
Definition at line 262 of file systematic_encoder.hpp.
Referenced by set_systematic_on().