kodo::backward_linear_block_decoder_policy Struct Reference
#include <backward_linear_block_decoder_policy.hpp>
Public Member Functions
backward_linear_block_decoder_policy (uint32_t start, uint32_t stop)
bool at_end () const
void advance ()
Advance the policy to the next index.
uint32_t index () const
Static Public Member Functions
static uint32_t max (uint32_t a, uint32_t b)
static uint32_t min (uint32_t a, uint32_t b)
Public Attributes
uint32_t m_start
The start value.
uint32_t m_stop
The end value.
Detailed Description
Policy object for determining the `direction` of the linear_block_decoder e.g. whether we will look for the first pivot from the beginning of the coefficients vector or in some other way.
The backward_linear_block decoder will search for pivots from the right of the encoding vector. E.g. if you see an encoding vector like:
<-----------+ direction of search for pivots
0 1 0 1 1 0 0 ^ ^ ^ | | | | | +----+ First coefficient searched | +--------+ First non zero coefficient +----------------+ Last coefficient searched
Definition at line 32 of file backward_linear_block_decoder_policy.hpp.
Constructor & Destructor Documentation
kodo::backward_linear_block_decoder_policy::backward_linear_block_decoder_policy (uint32_t start, uint32_t stop) [inline]
Construct the policy with the desired start and stop interval but ends included so [start:stop]
Parameters
start The first element to look at
stop The last element to look at
Definition at line 38 of file backward_linear_block_decoder_policy.hpp.
Member Function Documentation
bool kodo::backward_linear_block_decoder_policy::at_end () const [inline]
Returns
true if the policy is at the end
Definition at line 46 of file backward_linear_block_decoder_policy.hpp.
Referenced by advance(), and TEST().
uint32_t kodo::backward_linear_block_decoder_policy::index () const [inline]
Returns
the current index
Definition at line 59 of file backward_linear_block_decoder_policy.hpp.
Referenced by TEST().
static uint32_t kodo::backward_linear_block_decoder_policy::max (uint32_t a, uint32_t b) [inline], [static]
Parameters
a The first value
b The second value
Returns
the maximum value of the two input values
Definition at line 67 of file backward_linear_block_decoder_policy.hpp.
Referenced by TEST().
static uint32_t kodo::backward_linear_block_decoder_policy::min (uint32_t a, uint32_t b) [inline], [static]
Parameters
a The first value
b The second value
Returns
the minimum value of the two input values
Definition at line 75 of file backward_linear_block_decoder_policy.hpp.
Referenced by TEST().
The documentation for this struct was generated from the following file:
backward_linear_block_decoder_policy.hpp