kodo::forward_linear_block_decoder_policy Struct Reference
#include <forward_linear_block_decoder_policy.hpp>
Public Member Functions
forward_linear_block_decoder_policy (uint32_t start, uint32_t stop)
bool at_end () const
void advance ()
Advance the policy to the next index.
uint32_t index () const
Static Public Member Functions
static uint32_t max (uint32_t a, uint32_t b)
static uint32_t min (uint32_t a, uint32_t b)
Public Attributes
uint32_t m_start
The start value.
uint32_t m_stop
The end value.
Detailed Description
Policy object for determining the `direction` of the linear_block_decoder e.g. whether we will look for the first pivot from the beginning of the coefficients vector or in some other way.
The forward_linear_block decoder will search for pivots from the left of the encoding vector. E.g. if you see an encoding vector like:
+-----------> direction of search for pivots
0 1 0 1 1 0 0 ^ ^ ^ | | | | | +----+ Last coefficient searched | +--------------+ First non zero coefficient +----------------+ First coefficient searched
Definition at line 32 of file forward_linear_block_decoder_policy.hpp.
Constructor & Destructor Documentation
kodo::forward_linear_block_decoder_policy::forward_linear_block_decoder_policy (uint32_t start, uint32_t stop) [inline]
Construct the policy with the desired start and stop interval but ends included so [start:stop]
Parameters
start The first element to look at
stop The last element to look at
Definition at line 38 of file forward_linear_block_decoder_policy.hpp.
Member Function Documentation
bool kodo::forward_linear_block_decoder_policy::at_end () const [inline]
Returns
true if the policy is at the end
Definition at line 46 of file forward_linear_block_decoder_policy.hpp.
Referenced by advance(), kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::backward_substitute(), kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::forward_substitute_from_pivot(), kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::forward_substitute_to_pivot(), and TEST().
uint32_t kodo::forward_linear_block_decoder_policy::index () const [inline]
Returns
the current index
Definition at line 59 of file forward_linear_block_decoder_policy.hpp.
Referenced by kodo::bidirectional_linear_block_decoder< forward_linear_block_decoder_policy, symbol_decoding_status_counter< symbol_decoding_status_tracker< coefficient_value_access< coefficient_storage< coefficient_info< mutable_shallow_symbol_storage< storage_bytes_used< storage_block_info< finite_field_math< fifi::default_field< Field >::type, finite_field_info< Field, final_coder_factory_pool< shallow_rlnc_decoder< Field > > > > > > > > > > > > >::forward_substitute_from_pivot(), and TEST().
static uint32_t kodo::forward_linear_block_decoder_policy::max (uint32_t a, uint32_t b) [inline], [static]
Parameters
a The first value
b The second value
Returns
the maximum value of the two input values
Definition at line 67 of file forward_linear_block_decoder_policy.hpp.
Referenced by TEST().
static uint32_t kodo::forward_linear_block_decoder_policy::min (uint32_t a, uint32_t b) [inline], [static]
Parameters
a The first value
b The second value
Returns
the minimum value of the two input values
Definition at line 75 of file forward_linear_block_decoder_policy.hpp.
Referenced by TEST().
The documentation for this struct was generated from the following file:
forward_linear_block_decoder_policy.hpp